version: '3.8'

services:
  db:
    image: postgres:18.1-alpine3.22
    restart: always
    environment:
      POSTGRES_USER: gino
      POSTGRES_PASSWORD: tombesi
      POSTGRES_DB: nestjs
    ports:
      - "5499:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
